Repository strong-win/stock-craft, pull requests merged in 2021-11, with the labels that each got.

#24 #STRW-51 전체/거래가능 분리 및 시간 업데이트 로직 수정
  server/src/dto/player-update.dto.ts
  server/src/dto/trade-cancel.dto.ts
  server/src/dto/trade-response.dto.ts
  server/src/gateways/game.gateway.ts
  server/src/gateways/join.gateway.ts
  server/src/schemas/game.schema.ts
  server/src/schemas/player.schema.ts
  server/src/services/game.service.ts
  server/src/services/join.service.ts
  server/src/services/trade.service.ts
Labels: PR 🙇‍♂️ REVIEW REQUEST, Priority ❗️ Medium, Type 🛠 FEATURE

#25 #STRW-48 모델 성능 개선 및 안정화 II
  models/TIMEBAND/__init__.py
  models/TIMEBAND/core.py
  models/TIMEBAND/dashboard.py
  models/TIMEBAND/dataset.py
  models/TIMEBAND/loss.py
  models/TIMEBAND/metric.py
  models/TIMEBAND/model.py
  models/TIMEBAND/pretrained/sample/netD.pth
  models/TIMEBAND/pretrained/sample/netG.pth
  models/TIMEBAND/runner.py
  models/TIMEBAND/trainer.py
  models/TIMEBAND/utils/dataset.py
  models/TIMEBAND/utils/lstm_layer.py
  models/TIMEBAND/utils/time.py
  models/config.sample.json
  models/launcher.py
  models/logs/sample.log
  models/requirements.txt
  models/utils/args.py
  models/utils/color.py
  models/utils/device.py
  models/utils/logger.py
  models/utils/preprocess.py
Labels: PR 🙇‍♂️ REVIEW REQUEST, Priority ‼️ High, Type 🗳 TOTAL

#31 #STRW-58 stock generator column name 변경
  data/stock_generator.py
Labels: Extra 🏃 SIMPLE, PR 🙇‍♂️ REVIEW REQUEST, Priority ‼️ High, Type 🛠 FEATURE

#30 #STRW-57 ML Predicted data 생성파트 구현
  .gitignore
  models/TIMEBAND/core.py
  models/TIMEBAND/dashboard.py
  models/TIMEBAND/dataset.py
  models/TIMEBAND/model.py
  models/TIMEBAND/runner.py
  models/TIMEBAND/trainer.py
  models/utils/args.py
  models/utils/logger.py
Labels: PR 🙇‍♂️ REVIEW REQUEST, Priority ‼️ High, Type 🛠 FEATURE

#27 #STRW-52 figma prototype v0.2.1 반영(1) - 종목 리스트, 차트, 종합 거래 목록, 내 보유 주식
  app/src/components/Asset.tsx
  app/src/components/Chart.tsx
  app/src/components/Clock.tsx
  app/src/components/Corporations.tsx
  app/src/components/Corporations/Chart.tsx
  app/src/components/Corporations/MyStock.tsx
  app/src/components/Corporations/index.tsx
  app/src/components/Header.tsx
  app/src/components/Trade/TradeInput.tsx
  app/src/components/Trade/TradeList.tsx
  app/src/components/Trade/index.tsx
  app/src/containers/AssetWrapper.tsx
  app/src/containers/CorporationsWrapper.tsx
  app/src/containers/TradeWrapper.tsx
  app/src/index.tsx
  app/src/modules/user.ts
  app/src/pages/Play.tsx
  app/src/styles/Asset.css
  app/src/styles/Chart.css
  app/src/styles/Clock.css
  app/src/styles/Corporations.css
  app/src/styles/Header.css
  app/src/styles/Play.css
  app/src/styles/Trade.css
  app/src/styles/index.css
Labels: PR 🙇‍♂️ REVIEW REQUEST, Priority ❗️ Medium, Type 🛠 FEATURE

#36 #STRW-62 메인 페이지 피그마 시안에 맞게 수정
  app/src/components/Main/MainRoom.tsx
  app/src/components/Main/MainTItle.tsx
  app/src/components/Main/RoomCodeModal.tsx
  app/src/components/Main/index.tsx
  app/src/styles/Main.css
Labels: Extra 🏃 SIMPLE, PR 🙇‍♂️ REVIEW REQUEST, Priority ❗️ Medium, Type 🛠 FEATURE

#28 #STRW-55 APP 서버 내 아이템 처리 및 ML 서버 요청 구현
  server/docker-compose.dev.yml
  server/docker/Dockerfile.mock
  server/mock/index.ts
  server/mock/sample.ts
  server/package-lock.json
  server/package.json
  server/src/api/api.module.ts
  server/src/api/market.api.ts
  server/src/app.module.ts
  server/src/configs/mongoose.config.ts
  server/src/controllers/controllers.module.ts
  server/src/controllers/players.controller.spec.ts
  server/src/controllers/players.controller.ts
  server/src/dto/chart-request.dto.ts
  server/src/dto/chart-response.dto.ts
  server/src/dto/item-request.dto.ts
  server/src/dto/item-response.dto.ts
  server/src/dto/start-response.dto.ts
  server/src/dto/stock-response.dto.ts
  server/src/gateways/events.ts
  server/src/gateways/game.gateway.ts
  server/src/gateways/gateways.module.ts
  server/src/gateways/item.gateway.ts
  server/src/gateways/join.gateway.ts
  server/src/gateways/trade.gateway.ts
  server/src/providers/effect.provider.ts
  server/src/providers/providers.module.ts
  server/src/schemas/game.schema.ts
  server/src/schemas/item.schema.ts
  server/src/schemas/player.schema.ts
  server/src/schemas/trade.schema.ts
  server/src/services/game.service.ts
  server/src/services/item.service.ts
  server/src/services/join.service.ts
  server/src/services/services.module.ts
  server/src/services/stock.service.ts
  server/src/services/trade.service.ts
  server/src/states/game.state.ts
  server/src/states/player.effect.state.ts
  server/src/states/states.modules.ts
  server/src/states/stock.effect.state.ts
  server/src/utils/typeGuard.ts
Labels: PR 🙇‍♂️ REVIEW REQUEST, Priority ❗️ Medium, Type 🛠 FEATURE

#35 #STRW-61 FE 아이템 구현
  app/package-lock.json
  app/package.json
  app/src/assets/image.png
  app/src/components/Asset.tsx
  app/src/components/Clock.tsx
  app/src/components/Corporations/index.tsx
  app/src/components/Items.tsx
  app/src/components/ItemsAndTradeListTab.tsx
  app/src/components/Trade/TradeButton.tsx
  app/src/components/Trade/TradeInput.tsx
  app/src/components/Trade/TradeList.tsx
  app/src/components/Trade/TradeTab.tsx
  app/src/components/Trade/index.tsx
  app/src/components/Tutorial.tsx
  app/src/constants/item.ts
  app/src/containers/ItemsWrapper.tsx
  app/src/modules/sockets/events.ts
  app/src/modules/sockets/game.ts
  app/src/modules/sockets/index.ts
  app/src/modules/sockets/items.ts
  app/src/modules/sockets/join.ts
  app/src/modules/stock.ts
  app/src/modules/user.ts
  app/src/pages/Play.tsx
  app/src/styles/Items.css
  app/src/styles/Play.css
  app/src/styles/Trade.css
Labels: PR 🙇‍♂️ REVIEW REQUEST, Priority ❗️ Medium, Type 🛠 FEATURE

#39 #STRW-66 모델 레포 분리
  .github/ISSUE_TEMPLATE/sprint-issue-template.md
  .github/pull-request-template.md
  .github/workflows/lint-action-py.yml
  models/.gitignore
  models/README.md
  models/TIMEBAND/__init__.py
  models/TIMEBAND/core.py
  models/TIMEBAND/dashboard.py
  models/TIMEBAND/dataset.py
  models/TIMEBAND/loss.py
  models/TIMEBAND/metric.py
  models/TIMEBAND/model.py
  models/TIMEBAND/runner.py
  models/TIMEBAND/trainer.py
  models/TIMEBAND/utils/dataset.py
  models/TIMEBAND/utils/lstm_layer.py
  models/TIMEBAND/utils/time.py
  models/config.sample.json
  models/data/stock.sample.csv
  models/launcher.py
  models/requirements.txt
  models/utils/__init__.py
  models/utils/args.py
  models/utils/color.py
  models/utils/logger.py
Labels: Extra 🏃 SIMPLE, Priority ❕ Low, Type ⚙️ MAINTENANCE
